[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'ghostscript', 'tk']

[phases.install]
cmds = [
  'cd backend && pip install -r requirements.txt',
  'npm install',
  'cd frontend && npm install'
]

[phases.build]
cmds = ['npm run build:railway']

[start]
cmd = 'npm start'

